### ISSUE TITLE
add function documentation might be confusing

### ISSUE THREAD

**Issue by lzubiaur** [kikito/bump.lua#10]
Hi Kikito. First I must thank you for that awesome lib. Great job!

In the **add** function documentation it's said that the *x,y,w,h* parameters are the left, top, width, height which is correct for coordinate system with origin at the top-left (like Love). But for “Cartesian Coordinate System" (like cocos2dx) *x,y* are now the left,bottom of the rect.

It might be helpful for non Love users to specify in the doc that *x,y* depend on the system coordinate system. Thanks!

**Comment by kikito** [comment]
Hi, thanks!

I have never used Cocos2d (yet). So many things to learn! I would be very interested in seeing how bump works in other environments. 

And you are completely right, `x` and `y` are dependant on the system (actually they are *independent* but let's not get into semantics here). Do you think you can send me a pull request with the changes in the docs you want? I'm a bit busy atm.

**Comment by kikito** [comment]
I changed the docs - they now specify that what `x` and `y` represent depend on the host system. I also added examples for LÖVE, Corona and Cocos2d. 

Thanks for opening the issue and making bump.lua a bit better!

**Comment by lzubiaur** [comment]
Great. Thank you for creating bump!!
