### ISSUE TITLE
Suggestion: collision on scaling

### ISSUE THREAD

**Issue by raingloom** [kikito/bump.lua#19]
I know this would complicate things, but I'm working on a "physics" based platformer which is pretty much based on this feature.
The main issue I see is multiple collisions which could result in ambiguous responses.

**Comment by kikito** [comment]
Hi, could you ellaborate a bit about what you mean by "collision on scaling", exactly? It might be already supported, or a way to simulate it.

**Comment by raingloom** [comment]
Eg.: a rectangle "grows" on the local Y axis and pushes the one above it.
Now that I think about it... if we can determine what point it will grow from (which objects it will push itself away from), we can calculate where it will end up and what dynamic objects it now collides with, then push those away.
I'll try to implement it that way.
