### ISSUE TITLE
Automatic convertion to Cartesian coordinates?

### ISSUE THREAD

**Issue by zatherz** [kikito/bump.lua#22]
I recently switched from the Love2D engine to Amulet (http://amulet.xyz). In Love, the coordinates 0, 0 point to the top left corner. However, in Amulet, the coordinates 0, 0 point to the middle of the screen. Bump.lua seems to be using the first approach and I have noticed that my hitboxes are offcenter.

I think it'd be really nice to add an option to change the coordinate system to cartesian (basically just have it translate the coordinates).

**Comment by kikito** [comment]
Hi, thanks for taking the time to open an issue!

> Bump.lua seems to be using the first approach and I have noticed that my hitboxes are offcenter.

I don't think that is correct. bump makes no assumptions. Unless there is a bug somewhere, it just uses numbers and returns a result, which should be correct independently of which way is "up".

I suggest you look somewhere else to see where this misalignment is coming from. One thing which helps is drawing the box associated to each item (with `world:getRect(player)`) next to the box that the `player` already has. If they are different, this means that you either inserted it in the wrong location, or moved the player without telling the world with `world:move` or `world:update`. The fact that you are using different coordinates should not matter (again, unless there is a bug somewhere).

I am closing this issue now. If you think you have found a bug, please reopen.

**Comment by zatherz** [comment]
Sorry for bothering you. Indeed, there is something wrong with the placement of the actual thing. I'll look more into it.

**Comment by zatherz** [comment]
Well, it didn't take me long to find the issue!
Bump handles width and height differently from Amulet and that's the whole issue.
In Amulet, if you have a rectangle on 0, 0 with width 10, you will have a rectangle going from -5 to 5.
In Bump, if you have a rectangle on 0, 0 with width 10, you will have a rectangle going from 0 to 10.
This is of course easily fixed by doing `x - width/2` and `y - height/2` when adding the object to the Bump world.
Thank you a lot for help! I was thinking it would be nice if you were able to change the mode to the first one, so that confusion like this doesn't happen. Or at least have it say exactly how the width and height are processed.

**Comment by kikito** [comment]
> something like `require("bump").mode("half"))`

Sorry, that's not going to happen. Too much effort for too little gain.

> at least have it say exactly how the width and height are processed in the readme.

I just checked and it does indeed say that in the readme, on the section of `world:add`:

> * x,y,w,h: the rectangle associated to item in the world. They are all mandatory. w & h are the "width" and "height" of the box. x and y depend on the host system's coordinate system. For example, in LÖVE & Corona SDK they represent "left" & "top", while in Cocos2d-x they represent "left" & "bottom".

Do you think this is enough, or would you add/remove something?

**Comment by zatherz** [comment]
It's kind of vague, but honestly I have no idea how to word a note about this. I guess it can stay.
