### ISSUE TITLE
Is there a way to ignore collision?

### ISSUE THREAD

**Issue by 123samson456** [kikito/bump.lua#24]
I have an item in my game that has a collision so that it can be picked up by the player but only if he passes a certain requirement. if he doesnt however the item is blocking his way (which is not what i want).
Hence my question: Can I somehow ignore collisions by using a predefined function or can I create a collision filter (if so how would this filter look like code-wise)? 
Thanks in advance. Awesome collision library doing incredible work :D

**Comment by kikito** [comment]
A filter sounds like an ideal thing to use in your case. You can do that in two steps.

Step 1: define a function which takes the player as first parameter. The second parameter is any item the player can collide with. When the second parameter is the pickup object, and the player can pick it up, it should return `'cross'`. If the player can't pick it up, it should return `nil`. Also, if the item is not the pickup object (for example, if it's the ground, or a wall) it should return the appropiate value (usually this is `'slide'`). For example like this:

```
function playerFilter(player, item)
  if item.isPowerUp then
    if player.canPickPowerUp return 'cross' else return nil end
  else
    return 'slide'
  end
end
```

Step 2 is using this function when moving the player, as filter:

```
player.x, player.y, cols, len = world:move(player, goalX, goalY, playerFilter)
```

This will ignore powerups when `player.canPickPowerUp` is false.

Good luck!
