### ISSUE TITLE
world:move filter will not work with strings

### ISSUE THREAD

**Issue by cemcmd** [kikito/bump.lua#25]
I am trying to move an object with the filter 'cross' but it gives me this error:

LuaInterface.LuaScriptException: .\bump.lua:699: attempt to call upvalue 'filter' (a string value)

and here is the code:
local actualX, actualY, cols, len = world:move(mouse, mouseinfo.X, mouseinfo.Y, 'cross')

I tried it without a string and it just ignores it.

**Comment by davisdude** [comment]
Looking at the code, it appears as though the `filter` param is supposed to be a function. 

Looking at the README, it also looks like it should be a function:

```Lua
local playerFilter = function(item, other)
  if     other.isCoin   then return 'cross'
  elseif other.isWall   then return 'slide'
  elseif other.isExit   then return 'touch'
  elseif other.isSpring then return 'bounce'
  end
  -- else return nil
end
```

**Comment by cemcmd** [comment]
alright, worked for me.

**Comment by kikito** [comment]
👍 👍
