### ISSUE TITLE
Negative width in query rect

### ISSUE THREAD

**Issue by Bobbyjoness** [kikito/bump.lua#26]
Hello, I'm using bump for a game and I'm having a small issue. I am trying  to use queryRect to find enemies in my players attack range. The width I am sending to this function depends on the direction of the player which is a negative or positive 1 depending where the player is looking. When facing the positive direction queryRect works as expected but in the negative direction it fails silently. It doesn't even return the player. Idk if this is an intended feature or not. If it is, it would be helpful if queryRect errored when given invalid numbers.

**Comment by kikito** [comment]
You are absolutely right, thanks for reporting.

For clarity reasons, all rectangles in bump are supposed to be "positive" (no negative height or width). This check is missing in queryRect. I will add it.

**Comment by kikito** [comment]
Done! Thanks for creating this issue.
