### ISSUE TITLE
Make a tile no longer collidable ?

### ISSUE THREAD

**Issue by noomly** [kikito/bump.lua#38]
Hey,

First of all, thank you for making this library! I use it for a topdown zelda-like game and it is quite handy.
I'm facing a problem and I couldn't find if I could do it simply with your library. How do you manage objects that are not permanently collidable? For example I have a door which I can chose to open so when it's closed, it's collidable and when it's open, it's no longer collidable.

By the way, I'm using bump.lua with STI (Simple Tile Implementation) if it can help.

Thanks in advance

**Comment by kikito** [comment]
That's what the `filter` parameter is for. You should make it a function which:
* Returns `'slide'` when the tiles are collidable - such as a wall or a closed door
* Returns `nil` when they are not (they should be ignored in the collisions). For example empty tiles or open doors.

You could define your filter function like this:

``` lua
local playerFilter = function(item, other)
  if other.isDoor and other.isOpen then
    return nil
  else
    return 'slide'
  end
end
```
And here's how you would use it when moving a player:
```
local actualX, actualY, cols, len = world:move(player, goalX, goalY, playerFilter)
```
