### ISSUE TITLE
Need help for my bump.lua Java port

### ISSUE THREAD

**Issue by implicit-invocation** [kikito/bump.lua#39]
I made a Java port of this library to use with Libgdx

https://github.com/implicit-invocation/jbump

But I ran into a problem. The body gets stuck between tiles.

![http://i.imgur.com/yuCFSxE.png](http://i.imgur.com/yuCFSxE.png)

If I try to slide the body on the tiles, it will stop on the edges.  
I saw that bump.lua doesn't have this problem. Did you run into this problem before? And how did you solve that?

Thanks in advanced.

**Comment by kikito** [comment]
Hi there,

I gave a quick look at your code and nothing obvious jumped out.

> Did you run into this problem before?

Oh, yes. Many times.

> And how did you solve that?

A different solution each time. At the beginning I had to tweak the operations a little bit. A `<=` became a `<` here and there. Later on I had to add a bit of 'floating point coating' around my objects to prevent floating point numbers provoking collisions when they shouldn't.

In general, what prevents the collisions you mention to occur is the sorting of collisions: the `traverse` method returns collisions *sorted by proximity*. If an object is going over a tiled floor and it starts colliding with a new tile, it always should resolve colliding with the "current" tile first.

It doesn't work 100% of the time, but when it doesn't is usually well hidden (the current tile might "push" the player ahead a little bit).

The only way I know for sure to find the bug would be:

* Trying to replicate the problem with the smallest set of items possible (ideally, three: the player and two tiles) in jbump.
* Create the same scenario in bump.lua and check that it behaves differently.
* Add a bunch of print/printf to both versions until you find the place where they differ. 

Sorry I have no silver bullet for you. Good luck!

**Comment by implicit-invocation** [comment]
Thanks for your response.  
I tried to port bump.lua function by function.  
So if there's nothing wrong with my implementation, it should behave exactly like bump.lua.  

I found the problem. I tried to use a single instance for collision object (to reduce GC) and return a list of the same object for collision response. So no sorting can be done.
