### ISSUE TITLE
world:remove(item) causing an illogical error

### ISSUE THREAD

**Issue by netcodeyyy** [kikito/bump.lua#41]
When I add items to my game world by parsing them from map.lua into my Item class I add them to the collision world in bump too.
However when I want to delete one I get an error although it cannot be that there is a flaw in my code since it has literally come down to this:

`print( world:getRect( item ) )`
`if world:hasItem( item ) then`
`	world:remove( item )`
`end`
This is the error that I get:

> Error: utils/bump.lua:520: Item table: 0x0f7888f8 must be added to the world before getting its rect. Use world:add(item, x,y,w,h) to add it first. nil

The item has to be already added to the world since otherwise it wouldnt allow to remove it in the first place.
calling world:getRect( item ) manually gives me the 4 values x, y, w and h but the same function in world:remove( item ) causes the error.

pls help :(

**Comment by kikito** [comment]
Hi, if what you say is accurate, then the error is happening somewhere else. `getRect` is used a lot internally inside Bump. Can you include a short .love exemplifying the issue? If not, the stack trace of the error might be enough.

**Comment by netcodeyyy** [comment]
i pushed the newest version of my code to my project its called TopDownShooter.
The important parts (to my understanding) are 

- entities/item.lua (lines 37-48) -> line 48 works perfectly and prints the values when not a comment
- entities/player.lua (lines 103-107) -> calling handleCollision(other) on the item
- entities/itembase.lua (lines 13-23) -> the handleCollision(other) function 

 item.lua creates the object and adds it to the world. in player.lua the player is moved and his world collision is checked and if the player collides with the collision of the item the function in itembase.lua is called where the collision of said item is supposed to be deleted. (everything else is irrelevant afaik)

heres the error trace:
[https://imgur.com/WjBEtnc](url)

i hope this helps

**Comment by kikito** [comment]
Your stack trace points to something called EntityManager. This makes me think that your problem might be that you have several "lists" where the items exists. bump's list is its "world" variable. Are you removing entities from the EntityManager when you remove them from bump's world? If you are not, this might be the problem.

>  in player.lua the player is moved and his world collision is checked and if the player collides with the collision of the item the function in itembase.lua is called where the collision of said item is supposed to be deleted

In bump, there is no concept of "items colliding with collisions". Items collide with other items, and they produce a list of collisions.

**Comment by netcodeyyy** [comment]
ye seems like its a general problem concerning that since removing anything from the bump world results in that particular error. thanks for pointing me towards the source of the error i was searching at a place far from it ^^
also you are right about the colliding with collision thingy, badly worded by me.
thanks for the quick and detailed help

**Comment by kikito** [comment]
I did almost nothing, but you are welcome. Good luck finding that bug, I am closing this now.
