### ISSUE TITLE
Issue With Creating Items

### ISSUE THREAD

**Issue by mayadapples** [kikito/bump.lua#42]
Excuse me if this sounds dumb, but I'm new to bump and I have run into something that I couldn't find a fix to.

For some reason, I can only make new objects in the world unless the x and y inputs are tables, for instance:
`world:add(test, 80, 80, 20, 20)` would not work
but
`test = {x = 80, y = 80} ; world:add(test, test.x, test.y, 20, 20)` that **only** works.
And yes, it's only tables and only tables that have the same name.
This really seems confusing, or I just might be naive. Who know.

thanks.

**Comment by mayadapples** [comment]
Also I'm using LOVE 2D for more information.

**Comment by DanielPower** [comment]
In the first case, what is `test`? Is it a table? A string? What is the error code you're getting?

Please provide a minimal example that produces the error, or at the very least, provide the error message you're receiving.

**Comment by mayadapples** [comment]
Sorry, `test` refers to the body that I added in `world:add()` I was demonstrating that test and the table name must be the same as the item being introduced into the current world.

The error that I am receiving is: `bump.lua:625: table index is nil` which is in function `add`.

The code that is producing these errors is here:
local bump = require "bump"

```lua
local world = bump.newWorld()
world:add(wall, 80, 80, 30, 90)

function love.load()
	dr_wall = love.graphics.newImage("wall.png")
	dr_test = love.graphics.newImage("testImage01.png")
end
```

**Comment by mayadapples** [comment]
sorry the code got cut off a little include the `local bump =  require "bump"` to that.

**Comment by kikito** [comment]
The error indicates that the `item` you passed to bump is nil.

The variable called `wall` in your example must be undefined (you can test this by writing the following)

```
local world = bump.newWorld()
assert(wall, "wall is nil")
world:add(wall, 80, 80, 30, 90)

function love.load()
	dr_wall = love.graphics.newImage("wall.png")
	dr_test = love.graphics.newImage("testImage01.png")
end
```

But you make a good point; I should add checks on bump so if someone tries to pass a nil value it throws the proper error, so I will keep this issue open until I fix that. Thanks.

**Comment by mayadapples** [comment]
Cool, thanks for the help.
