### ISSUE TITLE
Allow World:remove to take the string name

### ISSUE THREAD

**Issue by flamendless** [kikito/bump.lua#43]
let's say i created something like this:
`
world:add({name="ground"},32,177,576,32)
`
i should be able to remove it using world:remove("ground")

Also, why not include bump_debug as a feature in the main bump library?

**Comment by kikito** [comment]
Hi, 

>  i should be able to remove it using world:remove("ground")

As a library developer, I want to implement features that at least most of my users will use. I don't think that particular feature is popular or demanded enough, so I will not implement that. However, feel free to fork and use it in yours if it suits your particular usecase.

> Also, why not include bump_debug as a feature in the main bump library?

The bump_debug library requires LÖVE to work. bump.lua is platform-independent and works with and without LÖVE.

Regards!
