### ISSUE TITLE
Enter and Exit question. (Not really an issue)

### ISSUE THREAD

**Issue by flamendless** [kikito/bump.lua#44]
Hi, awesome library by the way.

In physics (box2d) for love, there is a collision response called "enter" and "exit", are those two achievable using bump? That would really be great. If so, can you guide me on how to?

Another question, it seems that functions i put in "slide" and "touch" isnt called. Here is what im doing:
```
--adding item
world:add({name = "door", isSlide = true}, dx,dy,dw,dh)
--check collisions
	local playerFilter = function(item, other)
		if other.isSlide then return "slide"
		elseif other.isCross then return "cross"
		elseif other.isTouch then return "touch"
                elseif other.isSlide then return "slide"
		end
	end
	--movement
	local collisions,cols, len
	self.goal.y = self.goal.y + self.grav * dt
	local ax,ay,collisions,len = game.world:check(self,self.pos.x,self.pos.y,playerFilter)
	--validate collisions
	for i = 1, len do
		local other = collisions[i].other
		if other.isDoor then
			managers.gui:show(assets.gui.doors)
		elseif other.isStair then
			self.isinStair = true
			managers.gui:show(assets.gui.stairs)			
		elseif other.isSlide then
                       print("here" <----doesnt get printed
                end
	end
```

also, what is the easiest way to ask you questions regarding your libraries, im pretty sure posting a new issue(which it isnt) is not okay with you :/

**Comment by kikito** [comment]
> In physics (box2d) for love, there is a collision response called "enter" and "exit", are those two achievable using bump? That would really be great. If so, can you guide me on how to?

Achievable, yes. Easy and comfortable to do, no. Basically, what's required is that you maintain your own list of "entered items" for all items, calling "entered" or "exited" as the items "start touching" or "end touching". There's no built-in way of doing that.

> Another question, it seems that functions i put in "slide" and "touch" isnt called. Here is what im doing: [...]

I don't see anything immediately wrong with that code. Well, yes, you are making the same check twice here:

	local playerFilter = function(item, other)
		if other.isSlide then return "slide"   --> check for slide
		elseif other.isCross then return "cross"
		elseif other.isTouch then return "touch"
                elseif other.isSlide then return "slide"  --> check for slide again?
		end
	end

But that should make things go a tiny bit slower only - it should not make things "fail". I think that your problem might be somewhere else (maybe you forgot to set `isSlide` to true when you created the objects you want to "slide over"?

> what is the easiest way to ask you questions regarding your libraries, im pretty sure posting a new issue(which it isnt) is not okay with you :/

Creating issues is fine. Beware that sometimes it takes me a long time to respond.

I am closing this issue for now. Good luck finding the solution to your problem!
