### ISSUE TITLE
How to teleport a Object in world?

### ISSUE THREAD

**Issue by silrep2** [kikito/bump.lua#45]
Hi, friend
I want to 'teleport' a object to another position.
It seems not good to use world:move() because it will collide others
Now my strategy is to world:remove(obj) and then world:add(obj, newPosition).
Is there another way to do it?
Thanks.

**Comment by flamendless** [comment]
Please read the documentation carefully. Here is a snippet:

>This method always changes the rect associated to item, ignoring all collisions (use world:move for that). It returns nothing.

> You may use world:update if you want to "teleport" your items around. A lot of time, however, you want to move them taking collisions into account. In order to do that, you have world:move.

**Comment by kikito** [comment]
@flamendless is correct - use `world:update` instead of `world:move`.
